name: Base Branch Checker

on:
  pull_request_target:
    # By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened. 
    branches:
      - master
jobs:
  base_branch_check:
    runs-on: ubuntu-latest
    name: Base Branch Check
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Hello! It appears you have opened this Pull Request to the `master` branch.
                    - Please submit Pull Requests to the **`development` branch only**.
                    - Before Submitting your Pull Request, rebase your branch on `development` and fix any conflicts.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
