name: Base Branch Checker

on:
  pull_request_target:
    # By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened. 
    branches:
      - master
jobs:
  base_branch_check:
    runs-on: ubuntu-latest
    name: Base Branch Check
    steps:
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Comment PR if not coming from development or release/*
        if: |
          steps.branch-name.outputs.head_ref_branch != 'development' &&
          startsWith(steps.branch-name.outputs.head_ref_branch, 'release/') == false
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: >
            Thank you very much for your contribution. An automated check has shown that you have opened your Pull Request to the `master` branch. However, our project uses the `master` branch only for tested code.
            
            **Please submit your Pull Requests to the `development` branch**. In most cases, you don't have to create a new pull request but can simply [change the base branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add label if not coming from development or release/*
        if: |
          steps.branch-name.outputs.head_ref_branch != 'development' &&
          startsWith(steps.branch-name.outputs.head_ref_branch, 'release/') == false &&
          startsWith(github.event.comment.body, '/add-labels')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Invalid target
