name: Close stale PR containing merge conflicts
# This action will close automatically every PR already marked with "merge conflict" label
#   without activity for more than X days.
# This action is not adding a new label. It's an extension of the merge conflict action.
# The label will be added by "merge conflict" action.

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v7.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: -1
          # using 1 day for testing
          days-before-pr-stale: 30
          days-before-pr-close: 0
          any-of-labels: 'merge conflict'
          exempt-pr-labels: 'Internal, Documentation Needed'
          exempt-all-pr-assignees: true
          exempt-draft-pr: true
          operations-per-run: 300
          stale-pr-message: ''
          close-pr-message: 'Existing merge conflicts have not been addressed. This PR is considered abandoned.'
