name: Test Dependabot

on:
  push:
  pull_request:
jobs:
  Do nothing:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v3

    -
      name: Label the pull request to ignore for release note generation
      uses: actions-ecosystem/action-add-labels@v1
    -
      name: Set up Python 3.8
      uses: actions/setup-python@v5.5.0
