name: Test & Build
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7
      - name: Run Tests
        run: |
          echo "We are here"
