name: Build, Test, Deploy

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

env:
  GIT_TAG: ${{ github.event.release.tag_name }}
  GIT_BRANCH: ${GITHUB_REF#refs/*/}

jobs:
  playwithenv:
    runs-on: ubuntu-latest
    steps:
      -
        name: Do something
        run: |
          echo "GIT_TAG is set to ${GIT_TAG}"
          echo "GIT_BRANCH is set to ${GIT_BRANCH}"
